### ISSUE TITLE
Packing the demo VSCode extension with the server

### ISSUE THREAD

**Issue by rbasniak** [CXuesong/LanguageServer.NET#18]
Hello again,

How to you pack the extension into a VSIX package? I tried to use `VSCE PACKAGE` but it didn't work. It generates the package, but when I open it with 7zip the server is not in the package.

How do I publish the extension with the server together.

Another question, I see that in the extension you start the server using the `dotnet` command. I guess this way the person running the extension must have `dotnet core` installed, is that correct? Is there any way to overcome this limitation?

Thanks in advance,
Rodrigo Basniak

**Comment by CXuesong** [comment]
Hi Rodrigo,

Unfortunately I haven't ever got a chance to pack any extension based on LanguageServer.NET, since as you may have found out, that [CXuesong/MwLanguageServer](https://github.com/CXuesong/MwLanguageServer) is pretty much in hiatus state.

For now I'm trying to focus on the LSP server-side implementation. I might re-visit the client-side integration later, but sometimes we just need some more motivation and effort to push this library further :-) and I'm not ready for scaling this repo out yet. Sorry for that.

Thus you may try to start your own LSP client project in order to
* Invoke .NET-based LSP Server in a more robust way. You may compile your .NET Core application into executable (self-contained or framework-dependent).
* Put together the VSCode extension packaging and publishing process.
* Download any dependency (such as .NET Core Runtime) in case user's PC is lacking of them.

That being said, the DemoLanguageServer VSCode extension could be a good start point.

> Another question, I see that in the extension you start the server using the dotnet command. I guess this way the person running the extension must have dotnet core installed, is that correct? Is there any way to overcome this limitation?

Yes. And to resolve this limitation, you may compile your .NET Core application as self-contained executable. MSBuild will generate a set of files that enables your application to be executed on systems without .NET Core Runtime installed.

But this will also mean you will need to build separate editions of executables for each platform (Windows / Linux / MacOS, x86 / x64), and its total size will be fairly large. I suggest you placing the built executables on GitHub or elsewhere, and only download the edition compatible with user's platform when user first-time activates your extension.

**Comment by rbasniak** [comment]
Thank you so much for the detailed response, I'll see what I can achieve after my extension is in a more mature state. I'm just starting in this LSP world and there's a lot to do and learn before publishing.
