### ISSUE TITLE
Will it work in the docker container (linux)?

### ISSUE THREAD

**Issue by bushev** [CXuesong/LanguageServer.NET#20]
Hello, first of all, thank you for the great language server for C#!

Could you please help me to run it in a docker container?

My `Dockerfile` is:

```Dockerfile
FROM microsoft/dotnet:latest

WORKDIR /csharp-lsp

RUN dotnet add package CXuesong.LanguageServer.VsCode

# CMD <run lsp somehow>
```

The error that I'm getting (sorry, I'm not C# developer):

```
#5 0.426 Could not find any project in `/csharp-lsp/`.
#5 0.439 Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>
```

Basically, I need to figure out how to 2 things:

1. Install LSP
2. Rut with using *stdio* mode

Thanks!

**Comment by CXuesong** [comment]
First of all, this project is only a library on which you can write your own LSP server. For a sample demo project, see [\DemoLanguageServer](https://github.com/CXuesong/LanguageServer.NET/tree/master/DemoLanguageServer) directory. You need to start a C# (or VB / F#) project (something like `dotnet new console`) and then add my LSP library into that project. You will also need to write your own code to drive (i.e. put together) these all logics, and you may find all you need in [/DemoLanguageServer/Program.cs](https://github.com/CXuesong/LanguageServer.NET/blob/master/DemoLanguageServer/Program.cs).

Since you are the one responsible to drive all the LSP logics, it's up to you deciding what transport you want to run your LSP server). `DemoLanguageServer` is already using stdio (the one used by vscode-language-client) so that should meet your requirement.

**Comment by bushev** [comment]
Hey @CXuesong, 

Thank you for the explanation! I have not realized that it's a library. No issues then.
