### ISSUE TITLE
Problem with the LanguageServer.VsCode project

### ISSUE THREAD

**Issue by hazama-yuinyan** [CXuesong/LanguageServer.NET#8]
Hi, again! This time it's not a critical problem, but certainly annoying one.
After some actions on Visual Studio for Mac, it suddenly complains that, for example, the type Position exists both in "LanguageServer.VsCode, Version=0.0.0.0, publicKey=..." and "LanguageServer.VsCode, Version=0.2.0.0, publicKey=..."(Only the version number differs). I can't figure out what actions cause the problem(even reopening the solution may cause the problem), but it's really all of a sudden.
The build process doesn't complain about this, so you can run the dll without any problems, but after once that happened Intellisense doesn't work for the types defined in LanguageServer.VsCode.

Recreating the project would certainly solve the problem, so I've reported this just in case. This problem seems to only occur on Mac.

**Comment by CXuesong** [comment]
I assume you are adding reference in your project to the LanguageServer.NET NuGet package, instead of experimenting in the LanguageServer.NET solution containing the source code of `LanguageServer.VsCode`, right?

Hmmm… Have you tried to rebuild the solution?

**Comment by hazama-yuinyan** [comment]
> I assume you are adding reference in your project to the LanguageServer.NET NuGet package, instead of experimenting in the LanguageServer.NET solution containing the source code of LanguageServer.VsCode, right?

No. I'm using the repository as is and adding my own codes, based on that.
The problem has existed since I originally cloned it.

> Hmmm… Have you tried to rebuild the solution?

Yes, I've rebuilt it many times, but it doesn't solve it. Deleting the project and then re-adding the project might sometimes solve the problem but it arises again in no time.

**Comment by CXuesong** [comment]
Well, this time the problem seems a little bit difficult… I can think of nothing other than constant trying now 🤔

1. You may consider just referencing to the `LanguageServer.VsCode` project when writing the code, and then switch back to NuGet when publishing. Yes this is not satisfying, but in this way perhaps you may check whether the problem came from the project itself, or NuGet package.

2. it's interesting that while `JsonRpc.Standard` and `LanguageServer.VsCode` almost share the some configurations (they multi-target at net45/netstandard1.1, and their assemblies are signed), the IDE seems to only complain about the `LanguageServer.VsCode`  and nothing else. Still, you may try to change the `LanguageServer.VsCode.csproj` to make it only target at netstandard1.1 by removing the `<TargetFrameworks>` element, and add `<TargetFramework>netstandard1.1</TargetFramework>`. Then rebuild the package, and add it to your local NuGet package source. I'm not sure whether it's the same on Mac, but on Windows, we have [an configuration page for NuGet package sources](https://docs.microsoft.com/zh-cn/nuget/tools/package-manager-ui?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(VS.ToolsOptionsPages.NuGet_Package_Manager.Package_Sources)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396#package-sources), you may add a local folder to the sources list. Then just copy the built `nupkg` file into that folder. After that, clear your local NuGet package cache for `CXuesong.LanguageServer.VsCode` by removing the corresponding folder in `~/.nuget/packages/`. Finally, rebuild the project and see if that solves the problem.

**Comment by hazama-yuinyan** [comment]
Hmm, I have no idea of whether that solution really helps because VS is now silent but I did what you say, I guess. So only time will tell if it really helped or not ;-)

**Comment by hazama-yuinyan** [comment]
Unfortunately, the problem has occurred again...
I think it's not relevant because `~/.nuget/packages` doesn't have any cache in it for `LanguageServer.VsCode`.

**Comment by CXuesong** [comment]
Did you try to reference the `LanguageServer.VsCode` project directly? At least you can build and continue testing your language server locally.

**Comment by hazama-yuinyan** [comment]
Umm, you seem to really forget the implementation of the solution. It references the project directly when you cloned it from the repository.

I'm really wondering where the version '0.0.0.0' came from. I think it's the key to the solution of this problem.

**Comment by CXuesong** [comment]
Actually, I was too focused on and finally misunderstood "no" as in 

> No. I'm using the repository as is and adding my own codes, based on that.

🙈

So did you try to remove `net45` from `targetFrameworks` element in `LanguageServer.VsCode` project? Because you are targeting .NET Core so I think `netstanard` should work as well. Perhaps multi-targeting may cause the problem.

And you may try to remove the snk file for signing the the project. At this point, `LanguageServer.VsCode`would just be a normal .NET Standard project…

**Comment by hazama-yuinyan** [comment]
> Actually, I was too focused on and finally misunderstood "no" as in

>> No. I'm using the repository as is and adding my own codes, based on that.

Oh, I see.

Deleting .snk file seems to resolve the problem. At least VS is now silent. Thank you very much!

**Comment by CXuesong** [comment]
NP. Seems that  somehow snk doesn't work well on MacOS because my friend bumped into a similar issue, that the compiler complains about something on the signing when compiling `JsonRpc.Standard` project with `dotnet build` on MacOS…
